name: Build & Publish

on:
  push:
    branches: 
      - master
      - actions-dev

jobs:
  build:

    runs-on: "ubuntu-18.04"

    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.x'
    - name: Build
      run: |
        yarn install
        yarn start
    - name: Publish 2
      run: git subtree push --prefix dist "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" gh-pages
     
    - name: Publish
      run: git subtree push --prefix dist "https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git" gh-pages
