name: Build & Publish

on:
  push:
    branches: 
      - master
      - actions-dev

jobs:
  build:

    runs-on: "ubuntu-18.04"

    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.x'
    - name: Build
      run: |
        yarn install
        yarn start
    - name: Publish
      run: |
        git clone --quiet --branch="gh-pages" --depth=1 "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" .gh-pages
        ls -lah .gh-pages
        cp -r dist/* .gh-pages
        cd .gh-pages
        ls -lah
        git diff
        git add -A .
        git commit -q -m "Updating build pages"
        git push
     